### PR TITLE
new pdf for eq 43 and 44

### PR DESCRIPTION
**Pull request by johnjeihokim**
Here is the new pdf

### CODE REVIEW

**Comment by johnjeihokim** [comment]
equation43And44

**Comment by ndattani** [comment]
Hi @johnjeihokim! In the above screenshot, do you know why the subscript of `5` on `b5` is so close to the `b` at the end of the first line of Eq. 44, but is farther apart in Eq. 43? Perhaps a "half" space like `\,` or an even [smaller space](https://i.stack.imgur.com/mb9xK.png) like `\hspace{1sp}` might help. 

Also, you probably noticed that I had to say "first line of Eq. 44" in the above sentence, rather than just "Eq. 44". For this reason, both lines of Eq 44 should have their own Eqn numbers (44 and 45).

Thanks!

**Comment by johnjeihokim** [comment]
@ndattani I pushed my updated files. Here is a screenshot of the pdf:
43and44and45

**Comment by ndattani** [comment]
Very well done @johnjeihokim! Thank you!

**Pull request merged**
