### PR TITLE
Verifications for Equations 42 and 43 on page 14

### PR DESCRIPTION
**Pull request by johnjeihokim**
Hi Dr. Dattani, 
I added the verification for equations 42 and 43 on page 14. However, for some values of alpha (0.001, 0.5), the isequal function does not return true. Am I doing something wrong?

### CODE REVIEW

**Comment by ndattani** [comment]
Hi @johnjeihokim, thank you so much for this contribution!
This is truly excellent work.

You can see in the first sentence of Pg. 14 of the current version of the book, that the quadratization works for `alpha > 1`.  Therefore, out of the values of `alpha` that you tested, we were only expecting it to work for `alpha=2` and `alpha=15`. However you've found that it also worked for `alpha=1`(at least for this `k` value), which seems to indicate that the quadratization actually works for `alpha >=1` not just `>1`. The original [paper](https://par.nsf.gov/servlets/purl/10107499) seems to use the symbol `J` to represent `alpha`, and `J` does seem to be next to a lot of `>=` signs. 

I find it very interesting though to see what happens when `alpha=0.5`:
```
(LHS-RHS)'
ans =

        0
   0.5000
   0.5000
        0
   0.5000
        0
        0
        0
   0.5000
        0
```

We do get that the ground state energy is reproduced perfectly, as desired, and we can probably get _**all**_ states to be reproduced perfectly if we just added `0.5*f` where `f` is some function of the `b_i` variables.

Also for the `alpha=0.001` case we do have that the ground state energy is perfectly reproduced, as desired, and the rest of the numbers are extremely close to 1:

```
(LHS-RHS)'
ans =

        0
   0.9990
   0.9990
   0.99**8**0
   0.9990
```

This makes sense because LHS is just -1,0,0,0,0...,, and RHS for this very small value of `alpha` is probably close to being something like -1,-1,-1,-1...

**I think it would be neat for you to do the following:** 
- Add `5*b1b4 - b3`  to the LHS of Eq. 43 so that we know that this quadratization works even when the degree-k term on the left is _not isolated_. The right side will also have `5*b1b4 - b3`.
- Modify Eq. 43 of the book's source code [here](https://github.com/HPQC-LABS/Book_About_Quadratization/blob/master/Volume_1/Book_about_Quadratization.tex).
- Once you're done the above step, then add "LaTeX" to your resume in your "Skills" section :)
-  In a new line, expand the RHS of Eq. 43 so that we can see what the whole quadratic function looks like (without the brackets). Add this to the book's source code too :)

**Comment by ndattani** [comment]
@kwyip Hello! I've had some students write some MATLAB code to verify all the quadratizations in the book. It appears that the quadratization that you added, on what is Pg. 14 of the [current version of the book](https://github.com/HPQC-LABS/Book_About_Quadratization/blob/master/Volume_1/Book_about_Quadratization.pdf) (this is more updated than the arXiv version), works also for `alpha=1`, not just `alpha > 1`. Is this supposed to be the case? Also for Eq. 42, it would be nice if you could tell us which equation, or which line, from the original paper, matches Eq. 42 in the book. If you see Eq. 59 of the current version of the book, it says "Theorem 7 of [22]"  right below, so that the reader knows precisely where in the original paper, the equation comes from.

**Comment by ndattani** [comment]
@johnjeihokim  Thanks for the update! Were you able to compile the `.tex` file into a PDF successfully? If you were able to do that without getting any references showing up like (???) or [?], then this would be great. You might have to compile several times in a row, as [explained here](https://tex.stackexchange.com/q/53235/14527). Once you get a PDF that looks good, I'd recommend to push the PDF file and the `.log` file into your fork as well (but no other files please). Writing LaTeX code is one thing, but being able to compile it into a pretty PDF is a crucial component to being able to earnestly put LaTeX on your resume :)

I believe it was just one equation that you modified in the LaTeX file, so if you could also show me a screenshot of what the PDF looks like, in a comment on this Pull Request, then it would be very helpful for helping me to accept your Pull Request. The PDF viewer on GitHub can be slow, and while on the road I'm not always able to download a large PDF file and open it on the spot, so a screenshot of the one part that changed, would show me that the new version of the book is acceptable, without me having to download the PDF or rely on GitHub's PDF viewer.

**Comment by ndattani** [comment]
@johnjeihokim  My last comment here asked for a screenshot, and mentioned one of the reasons why it would be helpful :)

**Comment by johnjeihokim** [comment]
beforeChangesTo43

This is before

afterChangesTo43

And this is after

**Comment by ndattani** [comment]
Thank you @johnjeihokim! I only needed to see the part that you added, not the whole page. Please do the following and I think I'll be ready to accept your pull request :)

 - Label both equations with an equation number (so the factored form will be Eq. 43, and the unfactored form will be Eq. 44)
 -  Have the 2nd line in the unfactored version, start where the line above it starts (not where the arrow starts)
 - The plus sign at the end of the 1st line in the unfactored version, seems a bit too close to the symbol before it. Extra spacing to make it similar to the spacing around other plus signs would be nice!
 -  In the `.m` file, say "Eq 44 rather than Eq. 43".
 -  Is there some reason why the terms in the RHS are not given in the same order as in the book? If not, then I'd prefer the equation to match the book so that it's easier to read and verify that the quadratization has been verified.  
 - I'm curious how you expanded the factored RHS into the unfactored version? By hand? Or with symbolic software like Maple, Sage, Mathemtica, SymPy, WolframAlpha, etc.? It seems you've got the right expanded version because `LHS = RHS` in your MATLAB code :)

**Comment by johnjeihokim** [comment]
equation44

@ndattani  Hi Dr. Dattani, I think that this recent commit has all the changes you asked for.

I derived the unfactored version by just expanding the equation by hand.

**Comment by ndattani** [comment]
@johnjeihokim Very well done! Your pull request is approved and you should see yourself listed as a contributor [here](https://github.com/HPQC-LABS/Book_About_Quadratization/blob/master/README.md) and [here](https://github.com/HPQC-LABS/Book_About_Quadratization/graphs/contributors).

There was one question I asked in my last comment which appears to be unanswered: 
> "Is there some reason why the terms in the RHS are not given in the same order as in the book?"

Also I'm a bit confused about it saying [here](https://github.com/HPQC-LABS/Book_About_Quadratization/graphs/contributors) that you contributed the addition of 844 characters and removal of 845 characters. How could you have added so much with a net contribution of -1 character!?

Finally, recall in my last comment that I said "I only needed to see the part that you added, not the whole page", so you only needed to show me Eqs. 43-44 in the screenshot (anything more just makes the thread bulkier and makes me have to scroll down more!). See for example how the screenshot was provided [here](https://github.com/HPQC-LABS/Book_About_Quadratization/pull/52).

**Comment by johnjeihokim** [comment]
@ndattani there was no particular reason for my ordering of the terms in the matlab code. When I wrote the expanded the equation by hand, the equation was a bit messy and that is how I typed it into matlab. I later decided to make the RHS a bit 'prettier' for the pdf. 

It seems that most of the character deletions came from the push of the .log file in my third commit.

My apologies for making the screenshots so big, I just wanted to show that the references at the bottom of the page worked well.

**Comment by ndattani** [comment]
Hi @johnjeihokim. I merged your Pull Request into Master, but it might have been a bit too early. The PDF still looks like this:

image

Can you double check and make sure that everything is pushed correctly?
 
See [here](https://github.com/HPQC-LABS/Book_About_Quadratization/blob/master/Volume_1/Book_about_Quadratization.pdf).

**Comment by johnjeihokim** [comment]
@ndattani Yes you are right. Sorry about that. It seems I had pushed everything but the pdf. I made a new pull request with the new pdf with the right equations 43 and 44.

**Comment by kwyip** [comment]
@ndattani Sorry for late reply! 
Thank you for the update. I think $\alpha = 1$ can work, since it seems to pass every numerical test.
Eq.(42) of Pg. 14 was originally adapted from Eq. (21) of [16], as a special case of $a=1$. Originally you require $\alpha > a$, for positive $a$. Therefore the strict inequality is a sufficient condition that works for every positive $a$. But since in this special case (of $a = 1$) $a$ is small enough, $\alpha = a$  will work. 

- Originally from Eq. (21) of [16].

**Comment by ndattani** [comment]
@johnjeihokim  Are you not able to just update/re-open this Pull Request with the new version of the PDF? I don't see the need to make a new Pull Request for pushing a commit that was accidentally left out of this Pull Request!

@kwyip Thanks for the response! I'll look into it.

**Comment by johnjeihokim** [comment]
@ndattani Unfortunately I do not think that I can reopen this Pull request. When I tried pressing revert next to the merge commit a message popped up saying "Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged."

**Comment by ndattani** [comment]
@johnjeihokim You're right that [reverting the merge is probably the only way](https://stackoverflow.com/q/12674304/1271772) to reopen a *merged* pull request. Reversions can be complicated and ugly though, and I don't encourage them, so let's just work with your second pull request instead. Ideally we would not need two pull requests for one added "feature", so in the future I'd highly recommend to make sure the PDF is updated before saying that everything is done (and personally I should have also been more careful in double-checking the PDF in your last commit here).

**Pull request merged**
