### PR TITLE
Examples for bit flipping

### PR DESCRIPTION
**Pull request by CBaetz**
I have written an example for most of the uses of bit flipping mentioned. I have also labeled which use they are.

### CODE REVIEW

**Comment by ndattani** [comment]
Well done @CBaetz!  Thanks for your contribution here!

However, I find it extremely unusual that you'd add 6 commits for something so small. You really don't need to commit something like `%% Comment` and then commit again to remove it. Also if you forget one character, such as the `*` that you forgot in one of your commits, it's best to catch that before you `commit` anything. 

Perhaps you can try to [squash](https://www.git-tower.com/learn/git/faq/git-squash) your 6 commits into 1, before we merge your fork into the Master branch. You might even want to practice/test this in a separate repository of your own (which has no relation to this repository).

Other than the unusual number of commits here, you've done well on this task though!

**Comment by ndattani** [comment]
Hi @CBaetz, I still haven't accepted this pull request for a merge into the master branch, since I think it would be a good idea for you to first squash your commits (just push to this branch of your fork, and the pull request will be automatically updated). This would also be a good learning experience for you, meaning that if a situation like this were to ever come up in a work/team setting (whether with HPQC Labs or with anyone else), you would know what to do.

**Comment by CBaetz** [comment]
I have squashed all the commits into only 2 and changed the commit message accordingly.

**Comment by ndattani** [comment]
Thank you so much for squashing the commits! The pull request and its associated `code` additions, are now much easier to see. I'll take a final look as soon as I have time, and then hope to merge your contribution into the Master branch.

**Review by ndattani — APPROVED** [review]

**Pull request merged**
