### PR TITLE
Update deduc-reduc example

### PR DESCRIPTION
**Pull request by tanbur**

### CODE REVIEW

**Comment by ndattani** [comment]
Dear Richard, 
You did not notice that the new version leaks beyond 1 page?
I suppose there's not fundamental reason why each method has to be described on just 1 page, but every other method has had thought put into it in order to keep it to 1 page, so unless we really have to do otherwise, it would be nice for Deduc-Reduc to fit on one page. We don't even have to remove any content. Just  a few \vspace{-2mm} will do the trick.

Furthermore, F is written as  a function of x1, x2, x3, .... instead of b1, b2, b3, ....
Furthermore, F is described as "any polynomial" but it cannot be cubic or quartic because then why is the next equation written as H_{2-local}. 
In Part III, I often called the "leftover" function something like F_{2-local} .

It has been a while since I thought about deduc-reduc: Does F( {b_i} ) really need i >= 3 ?

Finally, the only difference between the "before" and "after" in this example is that b1b2(4 + b3 + b3b4) because 6b1b2. It's not clear in the paper how b1b2(4 + b3 + b3b4) becomes 6b1b2.

**Comment by tanbur** [comment]
Hi Nike,

I believe I've fixed the request in line with your comments, and added a sentence on how we chose the coefficient for b1b2.

F absolutely needs to be for i>= 3. Pick F = -100 b1 b2

Best wishes!

**Comment by ndattani** [comment]
Excellent! Though why does it say "unmerged" commits?

**Comment by ndattani** [comment]
Ok fixed it, excellent Richard!

**Pull request merged**
