### PR TITLE
Verification of SCM-BCR (Page 51, Eqn 171)

### PR DESCRIPTION
**Pull request by arpitarunkumaar**

### CODE REVIEW

**Comment by ndattani** [comment]
Well done @arpitarunkumaar!

I checked: `isequal(LHS,RHS)` and got 1. So this is a good start!

One thing this page is missing though, is an example of degree-5 function getting quadratized with the help of this method. Basically a PTR (positive term reduction) could be done on the positive degree-4 term and an NTR method could be used for the remaining negative degree-5 function. 

I think the LHS would require 2 auxiliary qubits if quadratized with any of the PTR methods, whereas the degree-4 term on the RHS would only require 1 auxiliary qubit. Is it possible to quadratize the remaining degree-5 function with only 1 auxiliary variable? Probably the only way to do this, that's currently described in the book, would be to use "Bit flipping (Ishikawa, 2011)" which is one page of the book, or to use something from the sections on "Methods that quadratize MULTIPLE terms with the SAME auxiliaries". Feel free to ask questions here or on Discord!

**Comment by arpitarunkumaar** [comment]
@ndattani I have quadratized the function with only 1 auxiliary variable by splitting it into 2 parts. The positive part has been reduced using PTR (Ishikawa's reduction) while the negative term has been reduced using NTR-ABCG-2. I hope that's what I was supposed to do. Please let me know if I need to make any changes :)

**Comment by ndattani** [comment]
I'm looking at it right now.

I was confused as to why you typed:

```
isequal(LHS_a,RHS_a)
isequal(LHS_b,RHS_b)
isequal(LHS_b,RHS_c)
isequal(LHS_b,RHS_d)
isequal(LHS_c,RHS_b)
isequal(LHS_c,RHS_c)
isequal(LHS_c,RHS_d)
```

which would cause the program to fail because `LHS_c` was never defined. 

It's good that you removed all this in your next commit, but I would highly recommend to push fewer commits (that means, finish the whole task and then push everything all at once at the end, rather than pushing 2 commits for one feature).

**Comment by arpitarunkumaar** [comment]
Got it! I was initially planning to do that but then thought of committing the first part just to show my progress and that I was still working on it. I'll take care of it from now. 
Also, do I need to squash the commit into one?

**Comment by ndattani** [comment]
I am looking at your full quadratization right now. 
To make it easier to follow, I would recommend for you to add it as an "Example" on the SCM-BCR page. Notice that almost every other page has an "Example" section, but SCM-BCR does not, so this is a chance for us to fix that. 

- [x] I would recommend for the example to be (for now) just the degree-5 monomial on the LHS. In the first line, the RHS can be exactly what it says in the "Summary" section, but with `k=5`. In the second line you can quadratize the positive and negative terms.
- [x] This can be added [here](https://github.com/HPQC-LABS/Book_About_Quadratization/blob/master/Volume_1/Book_about_Quadratization.tex) and then the `.tex` file can be recompiled into a new PDF. You may have to compile the PDF 4 times (3 times with `pdflatex` and 1 time with `bibtex` to make sure all references come out properly.
- [x] When you've successfully compiled the PDF, please paste a screenshot of the new "Example" section (but do not show a screenshot of the whole page, only the relevant lines that changed). 
- [ ] Please commit the new PDF and the new `.tex` file to the branch in this pull request. 
- [x] Once you're done the above, you can add "LaTeX" to your resume if you haven't already done so :)

If you need help with getting started with LaTeX, @ehuan2 did a good job of modifying the TeX file in March, and perhaps he can help you get started. I notice though that he is using Windows and you're using MacOS, so hopefully someone else, or some online tutorial could help you with LaTeX.

**Comment by arpitarunkumaar** [comment]
I think there has been some conflict while committing the example in the book. Let me know if anything requires changes.

**Comment by arpitarunkumaar** [comment]
Screenshot 2022-07-12 at 10 51 11 PM

Here's a screenshot of the example

**Comment by ndattani** [comment]
@arpitarunkumaar  Previously I had complained that you pushed 3 commits in order to introduce just one feature. Now you've pushed **6 commits** on 12 July alone! I would highly recommend to get everything ready (updated `.tex` file, updated `.pdf` file, etc.) and then to commit everything all at once so that it doesn't look so messy in the final version. This project has been going on for several years and we don't want to merge pull requests that will make the "history" look overly complicated or confusing.

Here's my comment on your above screenshot. Good work in getting this done. However Eq. 178 in your screenshot doesn't look right. If you're using an NTR (negative term reduction) then the LHS of Eq. 178 has to be negative. Also, even if you just add a negative sign, Eq. 178 still has more problems.

I would recommend to edit Eq. 176 to become  a bit more clear: b1b2b3b4bb5 -> (b1b2b3b4) -  (b1b2b3b4 - b1b2b3b4b5).
Now you can see that the first part is positive, and therefore can be reduced using a PTR, but the second part is negative. For this second part, I appreciate that you used NTR-ABCG2, but remember that I recommended to use something from the section called "Methods that quadratize MULTIPLE terms with the SAME auxiliaries". NTR-ABCG2 only quadratizes a single term, but the methods in the section I recommended can reduce _**multiple**_ terms. Since we are trying to quadratize the two-term component "-(b1b2b3b4 - b1b2b3b4b5)", then we want to use a multiterm quadratization rather than a single-term one :)

**Pull request merged**
