### PR TITLE
Fix logarithmic method

### PR DESCRIPTION
**Pull request by tanbur**
I think the previous method based on Theorem 4 also needs some changes but I'm not sufficiently sure to change it myself, since I find the matrix stuff confusing and verbose

### CODE REVIEW

**Comment by ndattani** [comment]
Got the email now.
Will be working on it shortly.

Thank you VERY much for the feedback about the matrix being hard to
understand. Can you perhaps tell me what makes it hard to understand or
what I can do to improve it? If it's hard for you, it's even harder for the
users, and that is certainly a concern for me.

With best wishes,
Nike

**Comment by tanbur** [comment]
Taking PTR-BCR-2, I actually can't make much sense of it at all.
My best guess is:
\alpha^{b_{a,1}} means \alpha^{b_{a_1}} from the upper equation and it's a typo.
\alpha^{b_{a}b_a} means \alpha^{b_{a_1}b_{a_2}} from the upper equation.
Do you also mean to sum over i and j in the last term? I only see an i.

Looking at PTR-BCR-3, my best guess is that you drop the i and j from \alpha^{b_{a_i}b_{a_j}} when looking it up in the matrix, and similarly for some of the other terms.

I had sort of assumed it was Einstein notation (which I've come across once and am not used to) but if it is I don't recognise it.
Sorry I can't be more help in telling you why it's hard when I still don't understand it.

**Comment by ndattani** [comment]
Wow. Usually when I want to comment in GitHub I visit the webpage and use the web interface, I didn't know that replying to an email would result in the email going public over here! Luckily I don't seem to have embarrassed myself, though it's always good to know who will have access to your words before writing anything!

PTR-BCR-2: You are completely right, there is a typo. b_{a_i} is meant to mean the i'th auxiliary variable, so for the alphas, I should have a comma between the 'a' and the '1' or '2'.

 Yes the last term should only have a sum over i. I will remove the j from the summation symbol

PTR-BCR-3: Ouch, more typos here. Rather than explaining everything I should just fix it and see if you understand it when it's fixed.

Actually SFR-BCR-1 seems not to have those typos. Can you look at that one and see if you're satisfied with it? The "example" section of course needs to be modified, but I wonder if you can make sense of the transformation description. This is actually the first one I typed up, and I believe I sent you an email where I showed this matrix notation before I pushed it into the repo.

I actually considered using Einstein summation convention, but have not used it anywhere in the paper. We don't have any need to use tensor notation with covariant and contravariant indices, so better might be a convention where anything with an "i" or "j" index is assumed to be summed over all possible values, except if there's an explicit summation sign with an upper limit saying the sum should be stopped earlier. This would remove the need for a lot of summation signs which are making it hard to fit things on one line and making everything look messier. However I don't think there is a desperate need for that.

With best wishes,
Nike

**Comment by ndattani** [comment]
Still PTR-BCR-3 is maybe a better example, but I've fixed up PTR-BCR-2 now. the "1" and the "2" in the \alpha^{b_a,1} and \alpha^{b_a,2} can maybe be replaced with " < m"  and "m" if you think it would help make it easier to understand.

selection_769

**Pull request merged**
